"""Заказы

Revision ID: 09b27dfc336e
Revises: a434ceccd14c
Create Date: 2020-03-06 18:47:44.363344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09b27dfc336e'
down_revision = 'a434ceccd14c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('commentary', sa.String(length=256), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_record_order_id'), 'order_record', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_record_student_id'), 'order_record', ['student_id'], unique=False)
    op.add_column('order', sa.Column('type_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'type_id')
    op.drop_index(op.f('ix_order_record_student_id'), table_name='order_record')
    op.drop_index(op.f('ix_order_record_order_id'), table_name='order_record')
    op.drop_table('order_record')
    # ### end Alembic commands ###
