"""Токен сообщества

Revision ID: 107148dd2717
Revises: d3068a885e5c
Create Date: 2020-03-05 04:06:04.578616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '107148dd2717'
down_revision = 'd3068a885e5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vk_group', sa.Column('token', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vk_group', 'token')
    # ### end Alembic commands ###
