"""Стоимость заказа

Revision ID: 224cd1e81df2
Revises: 09b27dfc336e
Create Date: 2020-03-06 18:53:03.384588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '224cd1e81df2'
down_revision = '09b27dfc336e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('cost', sa.Integer(), nullable=True))
    op.add_column('order_record', sa.Column('cost', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_record', 'cost')
    op.drop_column('order', 'cost')
    # ### end Alembic commands ###
