"""empty message

Revision ID: 89a66c4348f4
Revises: d4819371e524
Create Date: 2020-02-21 06:45:39.546472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89a66c4348f4'
down_revision = 'd4819371e524'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'group', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'group', type_='unique')
    # ### end Alembic commands ###
