"""empty message

Revision ID: b8439f7c5f6f
Revises: e760ac906a17
Create Date: 2020-03-19 15:52:05.518792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8439f7c5f6f'
down_revision = 'e760ac906a17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vk_group', sa.Column('name', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vk_group', 'name')
    # ### end Alembic commands ###
