"""Обновление сообществ

Revision ID: d3068a885e5c
Revises: f38f31ef855e
Create Date: 2020-03-05 03:45:25.249173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3068a885e5c'
down_revision = 'f38f31ef855e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vk_group', sa.Column('message', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vk_group', 'message')
    # ### end Alembic commands ###
