"""Время заказа

Revision ID: e760ac906a17
Revises: 224cd1e81df2
Create Date: 2020-03-06 20:23:34.744374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e760ac906a17'
down_revision = '224cd1e81df2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_record', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_order_record_timestamp'), 'order_record', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_record_timestamp'), table_name='order_record')
    op.drop_column('order_record', 'timestamp')
    # ### end Alembic commands ###
